spring:
  datasource:
    url: jdbc:mariadb://${{ DB_HOST }}:3306/${{ DB_NAME }}
    username: ${{ DB_USER }}
    password: ${{ DB_PASSWORD }}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect